---
domain: 
exposer:
watch-current-namespace: true
exposer: Route
apiserver: 192.168.64.82:8443
route-use-path: true
route-host:  fabric8.192.168.64.82.nip.io


#exposer: Ingress
#exposer: LoadBalancer
#
#exposer: NodePort
